services:
  db:
    image: postgres:15-alpine
    container_name: doc_portal_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: doc_portal
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d doc_portal"]
      interval: 10s
      timeout: 5s
      retries: 5  

  minio:
    image: minio/minio
    container_name: doc_portal_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  backend:
    build: ./backend
    container_name: doc_portal_api
    restart: always
    command: uvicorn app.api.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend/app:/app/app
      - ./backend/alembic:/app/alembic
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/doc_portal
    depends_on:
      db:
        condition: service_healthy  # Ждем, пока healthcheck базы не станет зеленым
      minio:
        condition: service_started  # Ждем, пока контейнер minio запустится

  worker:
    build: ./backend
    container_name: doc_portal_worker
    restart: always
    # Запускаем Celery-воркер, используя код из папки app
    command: celery -A app.celery_app worker --loglevel=info
    volumes:
      - ./backend/app:/app/app
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/doc_portal
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_started
      backend:
        condition: service_started

volumes:
  postgres_data:
  minio_data: