"""add_campaigns_and_ukep_workflow

Revision ID: b4f64279b23c
Revises: 
Create Date: 2026-03-31 21:13:30.055723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b4f64279b23c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Изменения для таблицы assigned_documents
    op.add_column('assigned_documents', sa.Column('campaign_id', sa.Integer(), nullable=False))
    op.add_column('assigned_documents', sa.Column('original_pdf_path', sa.String(), nullable=True))
    op.add_column('assigned_documents', sa.Column('director_signed_pdf_path', sa.String(), nullable=True))
    op.add_column('assigned_documents', sa.Column('final_signed_pdf_path', sa.String(), nullable=True))
    op.add_column('assigned_documents', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('assigned_documents', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('assigned_documents', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('DRAFT', 'WAITING_EMPLOYEE', 'FULLY_SIGNED', 'ERROR', name='docstatus'),
               existing_nullable=True)
    op.create_foreign_key(None, 'assigned_documents', 'document_campaigns', ['campaign_id'], ['id'])
    op.drop_column('assigned_documents', 'document_type')
    
    # Изменения для таблицы document_campaigns
    op.add_column('document_campaigns', sa.Column('hr_director_id', sa.String(), nullable=False))
    op.drop_column('document_campaigns', 'director_id')
    
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # Очищаем старые тестовые данные, так как они несовместимы с новой структурой
    op.execute('DELETE FROM assigned_documents')

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_campaigns', sa.Column('director_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('document_campaigns', 'hr_director_id')
    op.add_column('assigned_documents', sa.Column('document_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'assigned_documents', type_='foreignkey')
    op.alter_column('assigned_documents', 'status',
               existing_type=sa.Enum('DRAFT', 'WAITING_EMPLOYEE', 'FULLY_SIGNED', 'ERROR', name='docstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               postgresql_using='status::text::docstatus')
    op.alter_column('assigned_documents', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('assigned_documents', 'updated_at')
    op.drop_column('assigned_documents', 'final_signed_pdf_path')
    op.drop_column('assigned_documents', 'director_signed_pdf_path')
    op.drop_column('assigned_documents', 'original_pdf_path')
    op.drop_column('assigned_documents', 'campaign_id')
    op.create_table('kombu_message',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('visible', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('payload', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('queue_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['queue_id'], ['kombu_queue.id'], name=op.f('FK_kombu_message_queue')),
    sa.PrimaryKeyConstraint('id', name=op.f('kombu_message_pkey'))
    )
    op.create_index(op.f('ix_kombu_message_visible'), 'kombu_message', ['visible'], unique=False)
    op.create_index(op.f('ix_kombu_message_timestamp_id'), 'kombu_message', ['timestamp', 'id'], unique=False)
    op.create_index(op.f('ix_kombu_message_timestamp'), 'kombu_message', ['timestamp'], unique=False)
    op.create_table('kombu_queue',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('kombu_queue_pkey')),
    sa.UniqueConstraint('name', name=op.f('kombu_queue_name_key'))
    )
    op.create_table('celery_tasksetmeta',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('taskset_id', sa.VARCHAR(length=155), autoincrement=False, nullable=True),
    sa.Column('result', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('date_done', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('celery_tasksetmeta_pkey')),
    sa.UniqueConstraint('taskset_id', name=op.f('celery_tasksetmeta_taskset_id_key'))
    )
    op.create_table('celery_taskmeta',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.VARCHAR(length=155), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('result', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('date_done', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('traceback', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=155), autoincrement=False, nullable=True),
    sa.Column('args', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('kwargs', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('worker', sa.VARCHAR(length=155), autoincrement=False, nullable=True),
    sa.Column('retries', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('queue', sa.VARCHAR(length=155), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('celery_taskmeta_pkey')),
    sa.UniqueConstraint('task_id', name=op.f('celery_taskmeta_task_id_key'))
    )
    # ### end Alembic commands ###
